version: "3"
services:
  prometheus:
    image: prom/prometheus
    volumes: [ ./prometheus/:/etc/prometheus/ ]
    command: '--config.file=/etc/prometheus/prometheus.yml'
    ports: [ 9090:9090 ]
  grafana:
    image: grafana/grafana-enterprise
    volumes: [ ./grafana/:/etc/grafana/provisioning/ ]
    ports: [ 3060:3000 ]
    depends_on:
      - prometheus
